spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: product
          uri: http://localhost:8801
          predicates:
            - Path=/api/v2/**
        - id: user
          uri: http://localhost:8000
          predicates:
            - Path=/api/**
